config/routes.rb
# frozen_string_literal: true

Rails
  .application
  .routes
  .draw do
    resources :notifications, only: [:index] do
      member { patch :mark_as_read }
    end

    resources :users, only: %i[index show] do
      get 'bets', on: :member
    end

    resources :participations
    resources :bets do
      member { post 'resolve' }
    end

    get 'up' => 'rails/health#show', :as => :rails_health_check

    root 'home#index'

    # Authentication routes
    get '/auth/:provider/callback', to: 'sessions#create'
    get '/auth/failure', to: 'sessions#failure'
    get '/logout' => 'sessions#destroy'

    match '*unmatched', to: 'errors#not_found', via: :all
  end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :bet
  belongs_to :owner, class_name: 'User'

  validates :outcome, presence: true, unless: -> { outcome == false }
end

app/controllers/participations_controller.rb
# frozen_string_literal: true

# Participation Controller
class ParticipationsController < ApplicationController
  before_action :set_participation, only: %i[show edit update destroy]

  # GET /participations or /participations.json
  def index
    @participations = Participation.all
    @bets = Bet.all
  end

  # GET /participations/1 or /participations/1.json
  def show; end

  # GET /participations/new
  def new
    @bet = Bet.find_by(id: params[:bet_id])

    unless @bet
      flash[:error] = 'Invalid Bet ID. Please select a valid bet.'
      redirect_to root_path # Adjust the redirection as needed
      return
    end

    @participation = Participation.new
    @participation.bet_id = @bet.id

    @highest_p = @bet.participations.order(fee: :desc).limit(3)

    @owner_name = User.find_by(id: @bet.owner_id).username
  end

  # GET /participations/1/edit
  def edit; end

  # POST /participations or /participations.json
  def create # rubocop:disable Metrics/AbcSize,Metrics/MethodLength
    @participation = Participation.new(participation_params)
    @participation.owner_id = current_user.id
    @participation.anonymous = params[:participation][:anonymous] == '1'
    @participation.outcome = params[:participation][:outcome] == '1'

    Rails.logger.debug "Participation Information: #{@participation.inspect}"

    puts '111222333'
    puts @participation.inspect

    respond_to do |format|
      if user_has_enough_balance?(
           @participation.owner_id,
           @participation.fee
         ) && @participation.save
        deduct_balance(@participation.owner_id, @participation.fee) # Deduct the fee from the user's balance
        format.html do
          redirect_to participation_url(@participation),
                      notice: 'Participation was successfully created.'
        end
        format.json { render :show, status: :created, location: @participation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @participation.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /participations/1 or /participations/1.json
  def update
    respond_to do |format|
      if @participation.update(participation_params)
        format.html do
          redirect_to participation_url(@participation),
                      notice: 'Participation was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @participation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @participation.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /participations/1 or /participations/1.json
  def destroy
    @participation.destroy!

    respond_to do |format|
      format.html do
        redirect_to participations_url,
                    notice: 'Participation was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_participation
    @participation = Participation.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def participation_params
    params
      .require(:participation)
      .permit(:bet_id, :owner_id, :fee, :anonymous, :message)
  end

  def user_has_enough_balance?(user_id, participation_fee)
    user = User.find(user_id)
    user.balance.to_i >= participation_fee.to_i
  end

  def deduct_balance(user_id, amount)
    user = User.find(user_id)
    new_balance = user.balance.to_i - amount.to_i
    user.update(balance: new_balance)
  end
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/views/participations/_form.html.erb
<%= form_with(model: participation) do |form| %>
  <% if participation.errors.any? %>
    <div style="color: red">
      <h2>
        <%= pluralize(participation.errors.count, 'error') %> prohibited this
        participation from being saved:
      </h2>
      <ul>
        <% participation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :bet_id, value: @bet.id %>

  <div class="card detail-container">
    <%= form.label :anonymous, 'Enter your prediction!' %>
    <div class="radio-toolbar">
      <div class="radio-button-wrapper">
        <%= form.radio_button :outcome, '1', id: 'yes', checked: true %>
        <%=
          form.label :outcome,
                     'Yes!',
                     value: '1',
                     for: 'yes',
                     class: 'card',
                     checked: true
        %>
      </div>
      <div class="radio-button-wrapper">
        <%= form.radio_button :outcome, '0', id: 'nope' %>
        <%=
          form.label :outcome, 'Nope!', value: '0', for: 'nope', class: 'card'
        %>
      </div>
    </div>
  </div>
  <div class="card detail-container">
    <%= form.label :message %>
    <%=
      form.text_field :message,
                      class: 'card no-shadow',
                      placeholder: 'add a comment'
    %>
  </div>

  <div class="card detail-container">
    <%= form.label :fee, 'Enter your bet amount:' %>
    <div class="ects-input card" style="margin-top: 1rem">
      <p>ECT$</p>
      <%=
        form.number_field :fee,
                          min: @bet.minimum_fee,
                          placeholder: '1',
                          max: '180',
                          step: '0.5',
                          value: @bet.minimum_fee
      %>
    </div>
  </div>

  <%= form.submit 'BET !!!!', class: 'card' %>
<% end %>

app/views/participations/_participation.html.erb
<div id="<%= dom_id participation %>" class="card main-card-container">
  <div class="card">
    <strong>Title:</strong>
    <%= participation.bet.title %>
  </div>

  <p>
    <strong>Bet:</strong>
    <%= participation.bet_id %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= participation.owner_id %>
  </p>

  <p>
    <strong>Fee:</strong>
    <%= participation.fee %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= participation.message %>
  </p>

  <p>
    <strong>Anonymous:</strong>
    <%= participation.anonymous %>
  </p>

  <p>
    <strong>Outcome:</strong>
    <%= participation.outcome %>
  </p>
</div>

app/views/participations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Participations</h1>

<div id="participations" class="card">
  <% @participations.each do |participation| %>
    <%= render participation %>
    <p>
      <%= link_to "Show this participation", participation %>
    </p>
  <% end %>
</div>

<div id="bets" class="card">
  <% @bets.each do |bet| %>
    <%= link_to "New Participation #{bet.id}", new_participation_path(bet_id: bet.id) %>
  <% end %>
</div>

app/views/participations/new.html.erb
<main>
  <div class="card main-card-container">
    <h2>
      <% @bet ||= Bet.find_by(id: @participation.bet_id) %>
      <%= @bet.title %>
    </h2>
    <p class="bet-author">Made by: <%= @owner_name %></p>
    <div class="detail-container card">
      <h5>What's the bet?</h5>
      <p class="bet-description"><%= @bet.description %></p>
    </div>
    <%= render 'form', participation: @participation %>
  </div>
</main>
<div id="side" class="card">
  <div id="highest-bidders" class="card">
    <h4>Highest Bidders:</h4>
    <div id="comments-list">
      <% if @highest_p %>
        <% @i = 0 %>
        <% @highest_p.each do |h_participant| %>
          <% @i = @i + 1 %>
          <div class="card no-shadow">
            <div class="comment-name-amount-wrapper">
              <p class="placement">
                <strong><%= @i %>.</strong>
              </p>
              <% if !h_participant.anonymous %>
                <p class="comment-username">
                  <%= h_participant.owner.username %>
                </p>
              <% else %>
                <p class="comment-username">Anonymous</p>
              <% end %>
              <p>•</p>
              <p class="coment-fee">
                <strong><%= h_participant.fee %> <span class="currency">
                    ECT$</span
                  ></strong
                >
              </p>
            </div>
          </div>
        <% end %>
      <% else %>
      <% end %>
    </div>
  </div>
  <div id="comments-container" class="card">
    <h4>Comments:</h4>
    <div id="comments-list">
      <% @bet.participations.each do |comment_participation| %>
        <% if comment_participation.message %>
          <div class="card no-shadow">
            <div class="comment-name-amount-wrapper">
              <% if !comment_participation.anonymous %>
                <p class="comment-username">
                  <%= comment_participation.owner.username %>
                </p>
              <% else %>
                <p class="comment-username">Anonymous</p>
              <% end %>
              <p>•</p>
              <p class="coment-fee">
                <strong><%= comment_participation.fee %> <span class="currency">
                    ECT$</span
                  ></strong
                >
              </p>
            </div>
            <p class="comment-message"><%= comment_participation.message %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/participations/show.html.erb
<main><%= render @participation %></main>