config/routes.rb
# frozen_string_literal: true

Rails
  .application
  .routes
  .draw do
    resources :notifications, only: [:index] do
      member { patch :mark_as_read }
    end

    resources :users, only: %i[index show] do
      get 'bets', on: :member
    end

    resources :participations
    resources :bets do
      member { post 'resolve' }
    end

    get 'up' => 'rails/health#show', :as => :rails_health_check

    root 'home#index'

    # Authentication routes
    get '/auth/:provider/callback', to: 'sessions#create'
    get '/auth/failure', to: 'sessions#failure'
    get '/logout' => 'sessions#destroy'

    match '*unmatched', to: 'errors#not_found', via: :all
  end

app/models/user.rb
class User < ApplicationRecord
  has_many :participations, foreign_key: 'owner_id'
  has_many :bets, foreign_key: 'owner_id'
  has_many :notifications, dependent: :destroy

  after_create :enqueue_balance_job

  def to_s
    "#{first_name} #{last_name}"
  end

  def self.find_or_create_with_omniauth(auth_hash) # rubocop:disable Metrics/MethodLength,Metrics/AbcSize
    # identify user by provider + uid
    user =
      find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])

    # additional info about the user
    # which info is available depends on provider + scope
    Rails.logger.warn(auth_hash)
    if auth_hash['info']
      user.email = auth_hash['info']['email']
      user.first_name = auth_hash['info']['firstname']
      user.last_name = auth_hash['info']['lastname']
      user.status = auth_hash['info']['status']
      user.department = auth_hash['info']['department']
      user.studies = auth_hash['info']['studies']
    end
    user.access_token = auth_hash['credentials']['token']
    user.token_expires_at =
      DateTime.strptime(auth_hash['credentials']['expires_at'].to_s, '%s')
    user.save!
    user
  end

  private

  def enqueue_balance_job
    InitBalanceJob.perform_later(id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Users Controller
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/bets
  def bets
    @user = User.find(params[:id])

    if @user == current_user
      @bets = @user.bets
    else
      @bets = @user.bets.where(public: true)
    end

    puts "Bets: #{@bets.inspect}" # Debug statement
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html do
          redirect_to user_url(@user), notice: 'User was successfully created.'
        end
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if username_already_taken?
        flash[:alert] = 'Username is already taken.'
        format.html { redirect_to root_path }
        format.json do
          render json: {
                   error: 'Username is already taken'
                 },
                 status: :unprocessable_entity
        end
      elsif @user.update(user_params)
        format.html do
          redirect_to root_path, notice: 'User was successfully updated.'
        end
        format.html { redirect_to root_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html do
        redirect_to users_url, notice: 'User was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  def username_already_taken?
    existing_user = User.find_by(username: user_params[:username])
    existing_user && existing_user != @user
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :username)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :class_of, style: "display: block" %>
    <%= form.text_field :class_of %>
  </div>

  <div>
    <%= form.label :balance, style: "display: block" %>
    <%= form.text_field :balance %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Balance:</strong>
    <%= user.balance %>
  </p>
</div>

app/views/users/bets.html.erb
<main>
  <div id="my-bets" class="card main-card-container">
    <h3>My Bets</h3>
    <div id="my-bets-card-wrapper" class="card-wrapper">
      <% if @bets.any? %>
        <% @bets.each do |bet| %>
          <div class="card">
            <h4 class="title"><%= bet.title %></h4>
            <p>
              Created by:&nbsp;&nbsp;&nbsp;&nbsp;
              <strong><%= User.find_by(id: bet.owner_id)&.username %></strong>
            </p>
            <p class="minimum-bet">
              Minimum bet:&nbsp;&nbsp;&nbsp;&nbsp;
              <strong><%= bet.minimum_fee %><span class="currency"
                  >ECT$</span
                ></strong
              >
            </p>
            <%= link_to 'Show!', bet, class: 'card button' %>
          </div>
        <% end %>
      <% else %>
        <% if @user == current_user %>
          <div id="my-bets-card-wrapper" class="card-wrapper empty">
            <p>You currently have no running bets</p>
            <%= link_to 'Make a new bet', new_bet_path, class: 'card' %>
          </div>
        <% else %>
          <div id="my-bets-card-wrapper" class="card-wrapper empty">
            <p>
              <strong><%= @user.username %></strong> has no running bets
            </p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</main>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/mybets.html.erb
<main>
  <div id="my-bets" class="card">
    <h3>My bets</h3>
    <div id="my-bets-card-wrapper" class="card-wrapper">
      <% if @current_user_bets %>
        <% @current_user_bets.each do |bet| %>
          <div class="card">
            <p class="title"><%= bet.title %></p>
            <p class="minimum-bet">Minimum Bet: <%= bet.minimum_fee %> ECT$</p>
          </div>
        <% end %>
      <% else %>
      <% end %>
    </div>
  </div>
</main>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>